version: '3'

services:
  gitlab:
    build:
      context: .
    container_name: gitlab
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    restart: always

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
