FROM gitlab/gitlab-ce:latest

VOLUME ["/etc/gitlab", "/var/log/gitlab", "/var/opt/gitlab"]

EXPOSE 80 443 22

ENV GITLAB_OMNIBUS_CONFIG="external_url 'http://gitlab.local'; gitlab_rails['initial_root_password'] = 'UnSuperMotDePasse123!'"

CMD ["/assets/wrapper"]
